"""
Email sender for PROPIQ intake PDF reports.
Uses Resend API (preferred) or falls back to SMTP.
"""
import os
import smtplib
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from datetime import datetime


def _filename(client_name: str) -> str:
    safe = (client_name or "Client").replace(" ", "_")
    date_str = datetime.utcnow().strftime("%Y%m%d")
    return f"PROPIQ_Intake_{safe}_{date_str}.pdf"


def _send_via_resend(pdf_bytes: bytes, recipient: str, client_name: str) -> None:
    import resend  # type: ignore
    resend.api_key = os.environ["RESEND_API_KEY"]

    filename = _filename(client_name)
    b64 = base64.b64encode(pdf_bytes).decode()

    params = {
        "from": "PROPIQ <onboarding@resend.dev>",
        "to": [recipient],
        "subject": f"PROPIQ Client Report — {client_name or 'New Client'}",
        "text": (
            f"Hi,\n\n"
            f"Please find attached the client intake report for {client_name or 'your client'}.\n\n"
            f"Generated by the PROPIQ Client Intake system on "
            f"{datetime.utcnow().strftime('%d %B %Y')}.\n\n"
            f"Best regards,\nPROPIQ System"
        ),
        "attachments": [{"filename": filename, "content": b64}],
    }
    resend.Emails.send(params)


def _send_via_smtp(pdf_bytes: bytes, recipient: str, client_name: str) -> None:
    host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    user = os.environ.get("SMTP_USER", "")
    password = os.environ.get("SMTP_PASS", "")

    if not user or not password:
        raise RuntimeError("SMTP_USER and SMTP_PASS must be set in .env")

    filename = _filename(client_name)
    msg = MIMEMultipart()
    msg["From"] = f"PROPIQ <{user}>"
    msg["To"] = recipient
    msg["Subject"] = f"PROPIQ Client Report — {client_name or 'New Client'}"
    msg.attach(MIMEText(
        f"Hi,\n\nPlease find attached the client intake report for {client_name or 'your client'}.\n\n"
        f"Generated on {datetime.utcnow().strftime('%d %B %Y')}.\n\nBest regards,\nPROPIQ System",
        "plain"
    ))

    part = MIMEBase("application", "octet-stream")
    part.set_payload(pdf_bytes)
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)
    raw = msg.as_string()

    for port, use_ssl in [(587, False), (465, True)]:
        try:
            if use_ssl:
                with smtplib.SMTP_SSL(host, port) as s:
                    s.login(user, password)
                    s.sendmail(user, recipient, raw)
            else:
                with smtplib.SMTP(host, port) as s:
                    s.ehlo(); s.starttls(); s.ehlo()
                    s.login(user, password)
                    s.sendmail(user, recipient, raw)
            return
        except smtplib.SMTPAuthenticationError as e:
            raise RuntimeError(
                "Gmail rejected credentials. Enable 2-Step Verification at "
                "myaccount.google.com/security then regenerate the App Password."
            ) from e
        except Exception:
            continue

    raise RuntimeError("Could not connect to SMTP server on ports 587 or 465.")


def send_pdf_email(pdf_bytes: bytes, recipient: str, client_name: str) -> None:
    if os.environ.get("RESEND_API_KEY"):
        _send_via_resend(pdf_bytes, recipient, client_name)
    else:
        _send_via_smtp(pdf_bytes, recipient, client_name)
